baseurl = "/"
contentdir = "content"
publishdir = "public"

canonifyurls = true
relativeURLS = false

theme = "archie"
title = "Rejmank's brain dump"
languageCode = "en-us"
summaryLength = 42

copyright = "By Jiří Rejman, design by Vratislav Vanecek @1cha.co"


[author]
name = "Jiri Rejman"

[params]
description = "Rejmank's brain dump"
showFooterCredits = true
math = false
useIcon = true

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "feed"
[markup.goldmark.renderer]
unsafe = true
